services:
  timepoint:
    build:
      context: .
    container_name: ${TIMEPOINT_CONTAINER_NAME:-timepoint}
    depends_on:
      - timepoint-db
    environment:
      TIMEPOINT_CONFIG_PATH: /var/www/html/runtime/config.local.php
      TIMEPOINT_SQLITE_SOURCE: /var/www/html/legacy-db/timetracking.sqlite
      TIMEPOINT_DB_DRIVER: ${TIMEPOINT_DB_DRIVER:?Bitte TIMEPOINT_DB_DRIVER in .env oder Deployment-ENV setzen}
      TIMEPOINT_DB_HOST: ${TIMEPOINT_DB_HOST:?Bitte TIMEPOINT_DB_HOST in .env oder Deployment-ENV setzen}
      TIMEPOINT_DB_PORT: ${TIMEPOINT_DB_PORT:?Bitte TIMEPOINT_DB_PORT in .env oder Deployment-ENV setzen}
      TIMEPOINT_DB_NAME: ${TIMEPOINT_DB_NAME:?Bitte TIMEPOINT_DB_NAME in .env oder Deployment-ENV setzen}
      TIMEPOINT_DB_USER: ${TIMEPOINT_DB_USER:?Bitte TIMEPOINT_DB_USER in .env oder Deployment-ENV setzen}
      TIMEPOINT_DB_PASSWORD: ${TIMEPOINT_DB_PASSWORD:?Bitte TIMEPOINT_DB_PASSWORD in .env oder Deployment-ENV setzen}
    expose:
      - "80"
    volumes:
      - timepoint_runtime:/var/www/html/runtime
      - ./assets/db:/var/www/html/legacy-db:ro
    restart: unless-stopped

  timepoint-db:
    image: mariadb:11.4
    ports:
      - "3306:3306"
      # Bind on IP
      #- "100.x.y.z:5432:5432"
    container_name: ${TIMEPOINT_DB_CONTAINER_NAME:-timepoint-db}
    environment:
      MARIADB_DATABASE: ${TIMEPOINT_DB_NAME:?Bitte TIMEPOINT_DB_NAME in .env oder Deployment-ENV setzen}
      MARIADB_USER: ${TIMEPOINT_DB_USER:?Bitte TIMEPOINT_DB_USER in .env oder Deployment-ENV setzen}
      MARIADB_PASSWORD: ${TIMEPOINT_DB_PASSWORD:?Bitte TIMEPOINT_DB_PASSWORD in .env oder Deployment-ENV setzen}
      MARIADB_ROOT_PASSWORD: ${TIMEPOINT_DB_ROOT_PASSWORD:?Bitte TIMEPOINT_DB_ROOT_PASSWORD in .env oder Deployment-ENV setzen}
    volumes:
      - timepoint_mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  timepoint_runtime:
  timepoint_mariadb_data:
